version: '2.0'
services:
  db_postgres:
    image: postgres:9.5
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: u_xns
      POSTGRES_DB: xns
      POSTGRES_PASSWORD: 123456

    volumes:
      - /data/postgres/xns:/var/lib/postgresql/data


  xns_server:
    image: hub.iflytek.com/aiaas/xns
    ports:
      - 4567:4567
      - 8806:8806
    environment:
      NS_SERVER_LISTEN: :4567
      NS_ADMIN_LISTEN: :8806
      NS_PG_HOST: 10.1.87.70
      NS_PG_PORT: 5432
      NS_PG_USER: u_xns
      NS_PG_DB_NAME: xns
      NS_PG_PASSWORD: 123456
      NS_IP_SRC: /usr/local/xns/ip.src     #ip 地址池，
    volumes:
      - /data/log/xns:/usr/local/xns/log

