apiVersion: v1
kind: Pod
metadata:
  name: xns
  labels:
    k8s-app: xns
    version: v1
  annotations:
    - name: String
spec:
  restartPolicy: Always
  nodeSelector:
  containers:
    - name: xns_postgres
      image: postgres:9.5
      imagePullPolicy: IfNotPresent
      env: #指定容器中的环境变量
        - name: POSTGRES_USER
          value: u_xns
        - name: POSTGRES_DB
          value: xns
        - name: POSTGRES_PASSWORD
          value: 123456
      ports:
        - containerPort: 4567
          name: pg_port
          protocol: TCP
      volumeMounts: #挂载设置
        - name: db         #挂载设备的名字，与volumes[*].name 需要对应
          mountPath: /var/lib/postgresql/data   #挂载到容器的某个路径下
          readOnly: false
    - name: xns_server
      image: hub.iflytek.com/aiaas/xns
      imagePullPolicy: IfNotPresent
      env:                   #指定容器中的环境变量
        - name: NS_SERVER_LISTEN
          value: :24567
        - name: NS_ADMIN_LISTEN
          value: :28806
        - name: NS_PG_HOST
          value: 10.1.87.70
        - name: NS_PG_PORT
          value: 5432
        - name: NS_PG_USER
          value: u_xns
        - name: NS_PG_DB_NAME
          value:  xns
        - name: NS_PG_PASSWORD
          value: 123456
        - name: NS_IP_SRC
          value: /usr/local/xns/ip.src
      ports:
        - containerPort: 28806
          name: server_api
          protocol: TCP
        - containerPort: 24567
          name: admin_api
          protocol: TCP
      volumeMounts:
        - name: log
          mountPath: /usr/local/xns/log
          readOnly: false
  volumes:
    - name: log
      hostPath:
        path: /data/xns/log
    - name: db
      hostPath:
        path: /data/postgres/data
