package models

// this file is auto generated by _parse_test.go_TestStringer .
// do not edit it

import (
	"github.com/xfyun/xns/tools/str"
	"strconv"
	"fmt"
)

func(this Idc)String()string{
	return str.StringerOf("id",string(this.Id),"create_at",strconv.Itoa(int(this.CreateAt)),"update_at",strconv.Itoa(int(this.UpdateAt)),"description",string(this.Description),"name",string(this.Name))
}

func(this Group)String()string{
	return str.StringerOf("id",string(this.Id),"create_at",strconv.Itoa(int(this.CreateAt)),"update_at",strconv.Itoa(int(this.UpdateAt)),"description",string(this.Description),"name",string(this.Name),"idc_id",string(this.IdcId),"healthy_check_mode",string(this.HealthyCheckMode),"healthy_check_config",string(this.HealthyCheckConfig),"healthy_num",strconv.Itoa(int(this.HealthyNum)),"un_healthy_num",strconv.Itoa(int(this.UnHealthyNum)),"healthy_interval",strconv.Itoa(int(this.HealthyInterval)),"unhealthy_interval",strconv.Itoa(int(this.UnHealthyInterval)),"lb_mode",string(this.LbMode),"lb_config",string(this.LbConfig),"server_tags",string(this.ServerTags),"ip_alloc_num",strconv.Itoa(int(this.IpAllocNum)),"default_servers",string(this.DefaultServers),"port",strconv.Itoa(int(this.Port)))
}

func(this ServerGroupRef)String()string{
	return str.StringerOf("id",string(this.Id),"create_at",strconv.Itoa(int(this.CreateAt)),"update_at",strconv.Itoa(int(this.UpdateAt)),"description",string(this.Description),"server_ip",string(this.ServerIp),"group_id",string(this.GroupId),"weight",strconv.Itoa(int(this.Weight)))
}

func(this Pool)String()string{
	return str.StringerOf("id",string(this.Id),"create_at",strconv.Itoa(int(this.CreateAt)),"update_at",strconv.Itoa(int(this.UpdateAt)),"description",string(this.Description),"name",string(this.Name),"lb_mode",strconv.Itoa(int(this.LbMode)),"lb_config",string(this.LbConfig),"fail_over_config",string(this.FailOverConfig))
}

func(this GroupPoolRef)String()string{
	return str.StringerOf("id",string(this.Id),"create_at",strconv.Itoa(int(this.CreateAt)),"update_at",strconv.Itoa(int(this.UpdateAt)),"description",string(this.Description),"group_id",string(this.GroupId),"pool_id",string(this.PoolId),"weight",strconv.Itoa(int(this.Weight)))
}

func(this Route)String()string{
	return str.StringerOf("id",string(this.Id),"create_at",strconv.Itoa(int(this.CreateAt)),"update_at",strconv.Itoa(int(this.UpdateAt)),"description",string(this.Description),"name",string(this.Name),"service_id",string(this.ServiceId),"rules",string(this.Rules),"domains",string(this.Domains),"priority",strconv.Itoa(int(this.Priority)))
}

func(this Service)String()string{
	return str.StringerOf("id",string(this.Id),"create_at",strconv.Itoa(int(this.CreateAt)),"update_at",strconv.Itoa(int(this.UpdateAt)),"description",string(this.Description),"name",string(this.Name),"ttl",strconv.Itoa(int(this.TTL)),"pool_id",string(this.PoolId))
}

func(this ClusterEvent)String()string{
	return str.StringerOf("id",strconv.Itoa(int(this.Id)),"event",string(this.Event),"channel",string(this.Channel),"data",string(this.Data),"at",strconv.Itoa(int(this.At)),"expire_at",strconv.Itoa(int(this.ExpireAt)))
}

func(this Region)String()string{
	return str.StringerOf("id",string(this.Id),"create_at",strconv.Itoa(int(this.CreateAt)),"update_at",strconv.Itoa(int(this.UpdateAt)),"description",string(this.Description),"name",string(this.Name),"code",strconv.Itoa(int(this.Code)),"idc_affinity",string(this.IdcAffinity))
}

func(this Province)String()string{
	return str.StringerOf("id",string(this.Id),"create_at",strconv.Itoa(int(this.CreateAt)),"update_at",strconv.Itoa(int(this.UpdateAt)),"description",string(this.Description),"name",string(this.Name),"code",strconv.Itoa(int(this.Code)),"region_code",strconv.Itoa(int(this.RegionCode)),"country_code",strconv.Itoa(int(this.CountryCode)),"idc_affinity",string(this.IdcAffinity))
}

func(this City)String()string{
	return str.StringerOf("id",string(this.Id),"create_at",strconv.Itoa(int(this.CreateAt)),"update_at",strconv.Itoa(int(this.UpdateAt)),"description",string(this.Description),"name",string(this.Name),"code",strconv.Itoa(int(this.Code)),"province_code",strconv.Itoa(int(this.ProvinceCode)),"idc_affinity",string(this.IdcAffinity))
}

func(this CustomParamEnum)String()string{
	return str.StringerOf("id",string(this.Id),"create_at",strconv.Itoa(int(this.CreateAt)),"update_at",strconv.Itoa(int(this.UpdateAt)),"description",string(this.Description),"param_name",string(this.ParamName),"value",string(this.Value))
}

func(this Country)String()string{
	return str.StringerOf("id",string(this.Id),"create_at",strconv.Itoa(int(this.CreateAt)),"update_at",strconv.Itoa(int(this.UpdateAt)),"description",string(this.Description),"code",strconv.Itoa(int(this.Code)),"name",string(this.Name))
}

func(this User)String()string{
	return str.StringerOf("username",string(this.Username),"password",string(this.Password),"type",string(this.Type),"id",string(this.Id),"create_at",strconv.Itoa(int(this.CreateAt)),"update_at",strconv.Itoa(int(this.UpdateAt)),"description",string(this.Description))
}


func itoString(v interface{})string{
	stringer,ok := v.(fmt.Stringer)
	if ok{
		return stringer.String()
	}
	return fmt.Sprintf("%v",v)
}

